version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "yarn"
    directory: "/apps/strapi"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "yarn"
    directory: "/apps/ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
