// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmcuvwyimxsjiyxsllng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tY3V2d3lpbXhzaml5eHNsbG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NDUzMjgsImV4cCI6MjA1NzEyMTMyOH0.EWDYNJCjf0bsxday26yJbahrsdsEyQ4otQBWFae8ijU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);